"""
Proves `alembic upgrade head` actually applies cleanly against a throwaway
SQLite file — not just that a migration script was generated. Per this
repo's "verify, don't just claim" norm (`docs/SESSION_LOG.md` Session 3),
generating a migration and never running it is exactly the class of claim
this test exists to catch.
"""
from __future__ import annotations

import os
import sqlite3
from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic.config import Config

import foundation.config as config_module
from alembic import command

BACKEND_DIR = Path(__file__).resolve().parents[2]
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"

EXPECTED_TABLES = {
    "customers",
    "accounts",
    "transactions",
    "alerts",
    "model_runs",
    "rule_definitions",
    "rl_arm_state",
    "detection_feedback",
    "cases",
    "case_accounts",
    "case_status_history",
    "evidence",
    "notes",
    "reports",
    "case_feature_vector",
    "ai_interactions",
    "relationships",
    "users",
    "audit_log",
    "watchlist",
    "ingestion_log",
    "alembic_version",  # alembic's own bookkeeping table
}


@pytest.fixture()
def throwaway_database_url(tmp_path: Path) -> Iterator[str]:
    """Point `foundation.config.get_settings()` (which `alembic/env.py`
    reads) at a throwaway SQLite file for the duration of the test, then
    restore whatever was there before — this must never touch the real
    dev DB at `<repo_root>/data/tracex.db`.
    """
    db_path = tmp_path / "migration_verify.db"
    url = f"sqlite:///{db_path}"
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = url
    config_module.get_settings.cache_clear()
    try:
        yield url
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous
        config_module.get_settings.cache_clear()


def test_alembic_upgrade_head_applies_cleanly(throwaway_database_url: str) -> None:
    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "head")

    db_path = throwaway_database_url.removeprefix("sqlite:///")
    con = sqlite3.connect(db_path)
    try:
        tables = {
            row[0]
            for row in con.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
    finally:
        con.close()

    assert EXPECTED_TABLES == tables


def test_alembic_check_reports_no_drift_after_upgrade(throwaway_database_url: str) -> None:
    """After `upgrade head`, the live DB and the ORM metadata must agree —
    i.e. every model is actually represented in the migration, not just
    some of them."""
    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "head")
    # alembic.command.check raises AutogenerateDiffsDetected if the DB and
    # the models (target_metadata in env.py) disagree; a clean return means
    # no drift.
    command.check(cfg)


def test_alembic_downgrade_to_base_is_clean(throwaway_database_url: str) -> None:
    """The generated downgrade path must also actually run (proves the
    migration's `downgrade()` wasn't left as an autogenerate stub that
    silently fails)."""
    cfg = Config(str(ALEMBIC_INI))
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    db_path = throwaway_database_url.removeprefix("sqlite:///")
    con = sqlite3.connect(db_path)
    try:
        tables = {
            row[0]
            for row in con.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name != 'alembic_version'"
            )
        }
    finally:
        con.close()

    assert tables == set()
