"""initial schema

Revision ID: e4eb5cd58c9c
Revises: 
Create Date: 2026-07-09 13:06:31.076143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eb5cd58c9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('INDIVIDUAL', 'BUSINESS', name='entitytype'), nullable=False),
    sa.Column('pan', sa.Text(), nullable=True),
    sa.Column('aadhaar', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.Column('declared_annual_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('income_bracket', sa.Text(), nullable=True),
    sa.Column('employer', sa.Text(), nullable=True),
    sa.Column('kyc_status', sa.Enum('VERIFIED', 'PENDING', 'EXPIRED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('edd_status', sa.Enum('NOT_REQUIRED', 'REQUIRED', 'IN_PROGRESS', 'COMPLETE', name='eddstatus'), nullable=False),
    sa.Column('pep_status', sa.Boolean(), nullable=False),
    sa.Column('sanction_status', sa.Boolean(), nullable=False),
    sa.Column('risk_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_employer'), ['employer'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_pan'), ['pan'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('ingestion_log',
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('business_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_transactions', sa.Integer(), nullable=False),
    sa.Column('num_accounts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('file_hash')
    )
    op.create_table('model_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_type', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_hash', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('rl_arm_state',
    sa.Column('arm_id', sa.String(), nullable=False),
    sa.Column('a_matrix', sa.JSON(), nullable=False),
    sa.Column('b_vector', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('arm_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('INVESTIGATOR', 'ADMIN_COMPLIANCE', name='userrole'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('bank_id', sa.Text(), nullable=True),
    sa.Column('branch_city', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'CLOSED', 'FROZEN', name='accountstatus'), nullable=False),
    sa.Column('kyc_tier', sa.Text(), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_monthly_volume', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_branch_city'), ['branch_city'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_a', sa.String(), nullable=False),
    sa.Column('entity_b', sa.String(), nullable=False),
    sa.Column('shared_attribute', sa.Text(), nullable=False),
    sa.Column('value_hash', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_a'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['entity_b'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_definitions',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dsl', sa.JSON(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('watchlist',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'ACCOUNT', 'DEVICE', 'MERCHANT', 'COMPANY', name='watchentitytype'), nullable=False),
    sa.Column('entity_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('primary_account_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_REVIEW', 'ESCALATED', 'CLOSED_TP', 'CLOSED_FP', 'MONITORING', name='casestatus'), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', name='caselevel'), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='priority'), nullable=False),
    sa.Column('typology', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('network_risk_score', sa.Float(), nullable=True),
    sa.Column('network_risk_reasons', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Enum('FALSE_POSITIVE', 'TRUE_POSITIVE_SAR', 'ENHANCED_MONITORING', 'ESCALATED_COMPLIANCE', name='caseresolution'), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('evidence_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['primary_account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('transactions',
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_account', sa.String(), nullable=False),
    sa.Column('dest_account', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('UPI', 'NEFT', 'RTGS', 'IMPS', 'net_banking', 'mobile_app', 'ATM', 'branch_cash', 'cheque', 'unknown', name='channel'), nullable=False),
    sa.Column('txn_type', sa.Text(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('merchant_type', sa.Text(), nullable=True),
    sa.Column('is_laundering', sa.Integer(), nullable=False),
    sa.Column('from_bank', sa.Text(), nullable=True),
    sa.Column('to_bank', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Text(), nullable=True),
    sa.Column('source_file_hash', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dest_account'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['source_account'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['source_file_hash'], ['ingestion_log.file_hash'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_dest_account_timestamp', ['dest_account', 'timestamp'], unique=False)
        batch_op.create_index('ix_transactions_source_account_timestamp', ['source_account', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)

    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('agent', sa.Enum('RECOMMENDATION', 'COPILOT', name='aiagent'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('tools_called', sa.JSON(), nullable=True),
    sa.Column('facts', sa.JSON(), nullable=True),
    sa.Column('rule_anchors', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.Text(), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('investigator_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_interactions_case_id'), ['case_id'], unique=False)

    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('detection_type', sa.Enum('layering', 'round_trip', 'structuring', 'dormancy', 'profile_mismatch', name='detectiontype'), nullable=False),
    sa.Column('primary_account_id', sa.String(), nullable=False),
    sa.Column('account_ids', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='priority'), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=True),
    sa.Column('model_run_id', sa.String(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.run_id'], ),
    sa.ForeignKeyConstraint(['primary_account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_detection_type'), ['detection_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_risk_score'), ['risk_score'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.Enum('INVESTIGATOR', 'ADMIN', 'SYSTEM', 'AI', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('row_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('case_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SOURCE', 'MULE', 'SINK', 'NORMAL', name='accountrole'), nullable=True),
    sa.Column('hop_distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_accounts_case_id'), ['case_id'], unique=False)

    op.create_table('case_feature_vector',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('typology', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('FALSE_POSITIVE', 'TRUE_POSITIVE_SAR', 'ENHANCED_MONITORING', 'ESCALATED_COMPLIANCE', name='caseresolution'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_REVIEW', 'ESCALATED', 'CLOSED_TP', 'CLOSED_FP', 'MONITORING', name='casestatus'), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_REVIEW', 'ESCALATED', 'CLOSED_TP', 'CLOSED_FP', 'MONITORING', name='casestatus'), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_status_history_case_id'), ['case_id'], unique=False)

    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TRANSACTION', 'ACCOUNT', 'GRAPH_SNAPSHOT', 'DOCUMENT', 'PATTERN', 'NOTE_REF', name='evidencetype'), nullable=False),
    sa.Column('ref_id', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)

    op.create_table('notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('INVESTIGATOR', 'COPILOT', name='notesource'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_case_id'), ['case_id'], unique=False)

    op.create_table('reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SAR', 'STR', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'SUBMITTED', name='reportstatus'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('json_payload', sa.Text(), nullable=True),
    sa.Column('json_hash', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('fiu_reference', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('detection_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.Enum('FALSE_POSITIVE', 'TRUE_POSITIVE_SAR', 'ENHANCED_MONITORING', 'ESCALATED_COMPLIANCE', name='caseresolution'), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_feedback')
    op.drop_table('reports')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_case_id'))

    op.drop_table('notes')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_status_history_case_id'))

    op.drop_table('case_status_history')
    op.drop_table('case_feature_vector')
    with op.batch_alter_table('case_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_accounts_case_id'))

    op.drop_table('case_accounts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_alerts_detection_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_case_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_case_id'))

    op.drop_table('ai_interactions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index('ix_transactions_source_account_timestamp')
        batch_op.drop_index('ix_transactions_dest_account_timestamp')

    op.drop_table('transactions')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_cases_assigned_to'))

    op.drop_table('cases')
    op.drop_table('watchlist')
    op.drop_table('rule_definitions')
    op.drop_table('relationships')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_branch_city'))

    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('rl_arm_state')
    op.drop_table('model_runs')
    op.drop_table('ingestion_log')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_pan'))
        batch_op.drop_index(batch_op.f('ix_customers_employer'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
